# Generated by Django 3.2.19 on 2023-06-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='accepted_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_requirement', to='account.requirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profileofall')),
            ],
            options={
                'verbose_name_plural': 'Accepted Requiremnt',
                'db_table': 'accepted_requirement',
            },
        ),
    ]
