# Generated by Django 3.2.19 on 2023-07-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver_payment_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add  Payment For Driver',
                'db_table': 'driver_payment_amount',
            },
        ),
        migrations.CreateModel(
            name='driver_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicalname', models.CharField(max_length=200)),
                ('expriencesinyear', models.IntegerField()),
                ('driveroperatorname', models.CharField(max_length=200)),
                ('Aadharnumberfrontimage', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('Aadharnumberbackimage', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('alternet_mobilenumber', models.CharField(blank=True, max_length=12, null=True)),
                ('heavy_license', models.CharField(max_length=50)),
                ('emailId', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('license_image', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('driver_image', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('driver_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Driver Profile',
                'db_table': 'driveroperatorregistration',
            },
        ),
        migrations.CreateModel(
            name='request_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_driver', to='driver.driver_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profileofall')),
            ],
            options={
                'verbose_name_plural': 'Requested Driver',
                'db_table': 'request_driver',
            },
        ),
        migrations.CreateModel(
            name='driver_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('recycle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_payment', to='driver.driver_profile')),
            ],
            options={
                'verbose_name_plural': 'Driver Payment',
                'db_table': 'driver_payment',
            },
        ),
        migrations.CreateModel(
            name='driver_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('tahseel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tahseel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverAddress', to='driver.driver_profile')),
            ],
            options={
                'verbose_name_plural': 'Driver Address',
                'db_table': 'driveraddress',
            },
        ),
    ]
