# Generated by Django 3.2.19 on 2023-07-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='labour_contructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('labourwork', models.CharField(max_length=500)),
                ('emailId', models.CharField(blank=True, max_length=100, null=True)),
                ('lobourinnumber', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=20)),
                ('skilledlabour', models.IntegerField()),
                ('unskilledlabour', models.IntegerField()),
                ('professionallabour', models.IntegerField()),
                ('Aadharnumberfrontimage', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('Aadharnumberbackimage', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('alternativemobilenumber', models.IntegerField(blank=True, null=True)),
                ('labour_image', models.ImageField(upload_to='static/Uploaded/UserProfiles/')),
                ('labour_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Labour Contructor Profile',
                'db_table': 'labour_contructor',
            },
        ),
        migrations.CreateModel(
            name='labour_payment_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add  Payment For Labour',
                'db_table': 'labour_payment_amount',
            },
        ),
        migrations.CreateModel(
            name='request_labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
                ('labour_contructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_labour', to='labour_contructor.labour_contructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profileofall')),
            ],
            options={
                'verbose_name_plural': 'Requested Labour',
                'db_table': 'request_labour',
            },
        ),
        migrations.CreateModel(
            name='labour_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('recycle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_contructor', to='labour_contructor.labour_contructor')),
            ],
            options={
                'verbose_name_plural': 'Labour Payment',
                'db_table': 'labour_payment',
            },
        ),
        migrations.CreateModel(
            name='labour_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('tahseel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tahseel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labourAddress', to='labour_contructor.labour_contructor')),
            ],
            options={
                'verbose_name_plural': 'Labour Address',
                'db_table': 'labouraddress',
            },
        ),
    ]
