# Generated by Django 3.2.19 on 2023-07-02 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='heavyvehivalregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehical_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=50)),
                ('ownername', models.CharField(max_length=300)),
                ('vehicleregistrationnumber', models.CharField(max_length=100)),
                ('Aadharnumberfrontimage', models.ImageField(upload_to='Vehicle-Owners/UserProfiles/')),
                ('Aadharnumberbackimage', models.ImageField(upload_to='Vehicle-Owners/UserProfiles/')),
                ('vehicle_image', models.ImageField(upload_to='Vehicle-Owners/UserProfiles/')),
                ('vehicle_image_back', models.ImageField(upload_to='Vehicle-Owners/UserProfiles/')),
                ('vehicle_image_left', models.ImageField(upload_to='Vehicle-Owners/UserProfiles/')),
                ('vehicle_image_right', models.ImageField(upload_to='Vehicle-Owners/UserProfiles/')),
                ('manufacture_date', models.DateField()),
                ('alternativemobilenumber', models.CharField(max_length=20)),
                ('vehiclemodelnumber', models.CharField(max_length=100)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Heavy Vehicle',
                'db_table': 'heavyvehivalregistration',
            },
        ),
        migrations.CreateModel(
            name='vehicle_payment_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add  Payment For Vehicle ',
                'db_table': 'payment_amount',
            },
        ),
        migrations.CreateModel(
            name='vehicle_user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('recycle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heavyvehivalregistration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_owner.heavyvehivalregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_payments', to='vehicle_owner.vehicle_user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='user_coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField()),
                ('discount_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_owner.discount_coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='request_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
                ('heavyvehivalregistration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_vehicle', to='vehicle_owner.heavyvehivalregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to='account.profileofall')),
            ],
            options={
                'verbose_name_plural': 'Requested Vehicle',
                'db_table': 'request_vehicle',
            },
        ),
        migrations.AddField(
            model_name='heavyvehivalregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owners', to='vehicle_owner.vehicle_user_profile'),
        ),
        migrations.CreateModel(
            name='heavyvehicleaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('heavyvehivalregistration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleaddress', to='vehicle_owner.heavyvehivalregistration')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('tahseel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tahseel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_address', to='vehicle_owner.vehicle_user_profile')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Address',
                'db_table': 'heavyvehicleaddress',
            },
        ),
    ]
