# Generated by Django 3.2.19 on 2023-07-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcontractorregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractorname', models.CharField(max_length=100)),
                ('firmname', models.CharField(max_length=500)),
                ('typeofwork', models.CharField(max_length=100)),
                ('emailId', models.CharField(blank=True, max_length=50, null=True)),
                ('expriencesinyear', models.IntegerField()),
                ('license_number', models.CharField(max_length=50)),
                ('Aadharnumberfrontimage', models.ImageField(upload_to='Subcontructor-Owners/UserProfiles/')),
                ('Aadharnumberbackimage', models.ImageField(upload_to='Subcontructor-Owners/UserProfiles/')),
                ('mobilenumber', models.CharField(max_length=20)),
                ('subcontractor_image', models.ImageField(upload_to='Subcontructor-Owners/UserProfiles/')),
                ('subcontractor_image_back', models.ImageField(upload_to='Subcontructor-Owners/UserProfiles/')),
                ('subcontractor_image_left', models.ImageField(upload_to='Subcontructor-Owners/UserProfiles/')),
                ('subcontractor_image_right', models.ImageField(upload_to='Subcontructor-Owners/UserProfiles/')),
                ('is_active', models.BooleanField(default=1)),
                ('subcontructor_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subcontructor_Profile',
                'db_table': 'subcontractorregistration',
            },
        ),
        migrations.CreateModel(
            name='subcontructor_payment_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add  Payment For Subcontructor',
                'db_table': 'subcontructor_payment_amount',
            },
        ),
        migrations.CreateModel(
            name='subcontructor_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('recycle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontructor_payment', to='sub_contructor.subcontractorregistration')),
            ],
            options={
                'verbose_name_plural': 'subcontructor Payment',
                'db_table': 'subcontructor_payment',
            },
        ),
        migrations.CreateModel(
            name='subcontructor_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('tahseel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tahseel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubcotructorAddress', to='sub_contructor.subcontractorregistration')),
            ],
            options={
                'verbose_name_plural': 'SubContructor Address',
                'db_table': 'subcontructoraddress',
            },
        ),
        migrations.CreateModel(
            name='request_subcontructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
                ('subcontractorregistration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_subcontructor', to='sub_contructor.subcontractorregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profileofall')),
            ],
            options={
                'verbose_name_plural': 'Requested Subcontructor',
                'db_table': 'request_subcontructor',
            },
        ),
    ]
