# Generated by Django 3.2.19 on 2023-07-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_payment_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add  Payment For General User',
                'db_table': 'user_payment_amount',
            },
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('recycle', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to='df_user.user_profile')),
            ],
            options={
                'verbose_name_plural': 'General User Recieved Payment',
                'db_table': 'user_payment',
            },
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.district')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.state')),
                ('tahseel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tahseel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAddress', to='df_user.user_profile')),
            ],
            options={
                'verbose_name_plural': 'User Address',
                'db_table': 'user_address',
            },
        ),
    ]
