# Generated by Django 3.2.19 on 2023-05-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileofall',
            name='role',
            field=models.CharField(choices=[('heavy_vehicle', 'heavy_vehicle'), ('driver', 'driver'), ('subcontructor', 'subcontructor'), ('labour', 'labour'), ('user', 'user')], max_length=20),
        ),
    ]
